[build]
target = "aarch64-linux-android"

[target.aarch64-linux-android]
linker = "/Users/haojiejack/Library/Android/sdk/ndk/android-ndk-r27c/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android33-clang"
ar = "/Users/haojiejack/Library/Android/sdk/ndk/android-ndk-r27c/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
rustflags = [
  "-l",
  "clang_rt.builtins-aarch64",
  "-L",
  "/Users/haojiejack/Library/Android/sdk/ndk/android-ndk-r27c/toolchains/llvm/prebuilt/darwin-x86_64/lib/clang/18/lib/baremetal",
]

[env]
CC_aarch64-linux-android = "/Users/haojiejack/Library/Android/sdk/ndk/android-ndk-r27c/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android33-clang"
AR_aarch64_linux_android = "/Users/haojiejack/Library/Android/sdk/ndk/android-ndk-r27c/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
CARGO_TARGET_AARCH64_LINUX_ANDROID_AR = "/Users/haojiejack/Library/Android/sdk/ndk/android-ndk-r27c/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
BINDGEN_EXTRA_CLANG_ARGS = "--sysroot=/Users/haojiejack/Library/Android/sdk/ndk/android-ndk-r27c/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/"
